[Logs]
	#If true, all missing optional properties
	#and their default values will be logged
	#when parsing custom machines jsons.
	log_missing_optional = false
	#When parsing custom machines json files,
	#some properties can be read with 2 serializers.
	#Set this to true to log when the first serializer throw an error,
	#even if the second succeed.
	log_first_either_error = false
	#Configure what logs will be printed in the custommachinery.log file.
	#Only logs with level higher or equal than selected will be printed.
	#FATAL > ERROR > WARN > INFO > DEBUG > ALL
	#Allowed Values: FATAL, ERROR, WARN, INFO, DEBUG, ALL
	debug_level = "INFO"

[General]
	#Defines the _default_ color for machine casings as items or blocks. (Hex color with alpha at start) Has to be defined both server and clientside!
	general_casing_color = "#FFFF4900"
	#Defines the _default_ color for EMI/JEI chance text color. (Hex color without alpha) Has to be defined both server and clientside!
	chance_color = "#FFFFFF"
	#Defines the time in ticks that the machine should check for a structure update.
	#20 ticks = 1 second. Default: 5
	# Default: 5
	# Range: > 1
	check_structure_ticks = 5
	#Defines the time in ticks that the machine should check for a recipe update.
	#20 ticks = 1 second. Default: 80
	# Default: 20
	# Range: > 1
	check_recipe_ticks = 20
	#Defines the number of max parallel recipes that can be run on multiblocks. If this number is below than any on [parallel hatch] config path, it will use the max value of them instead.
	# Default: 256
	# Range: > 1
	maxParallel = 256

[Structure]
	#Defines if it should break and place the non-matching blocks on trying to place structure. Default: true
	should_replace = true
	#Defines if should sent a message to the player for each replaced block. Default: true
	replaceMessage = true
	#Defines if should sent a message to the player for each missing block. Default: true
	missingBlockMessage = true
	#Defines if should sent a message to the player for each error on place block. Default: true
	errorMessage = true

[Rendering]
	#The time in milliseconds the structure requirement
	#structure will render in world when clicking
	#on the icon in the jei recipe.
	# Default: 10000
	# Range: > 1
	structure_render_time = 10000
	#The time in milliseconds each blocks will be shown
	#when using a block tag in a structure.
	# Default: 1000
	# Range: > 1
	block_tag_cycle_time = 1000

[Directories]
	#A folder name where MMR will load machine structure json.
	#These folder must be under the "data/<namespace>" folder.
	machine_directory = "machines"
	#A list of folder names where MMR will load controller models json. These folders must be under the 'assets/namespace/models' folder.
	model_folders = ["controller", "controllers"]
