[tiny]
	#Energy storage size of the energy hatch.
	# Default: 2048
	# Range: > 1
	size = 2048
	#Defines the transfer limit for RF/FE things. 
	#IC2's transfer limit is defined by the voltage tier.
	# Default: 128
	# Range: > 1
	transfer_rate = 128

[small]
	#Energy storage size of the energy hatch.
	# Default: 4096
	# Range: > 1
	size = 4096
	#Defines the transfer limit for RF/FE things. 
	#IC2's transfer limit is defined by the voltage tier.
	# Default: 512
	# Range: > 1
	transfer_rate = 512

[normal]
	#Energy storage size of the energy hatch.
	# Default: 8192
	# Range: > 1
	size = 8192
	#Defines the transfer limit for RF/FE things. 
	#IC2's transfer limit is defined by the voltage tier.
	# Default: 512
	# Range: > 1
	transfer_rate = 512

[reinforced]
	#Energy storage size of the energy hatch.
	# Default: 16384
	# Range: > 1
	size = 16384
	#Defines the transfer limit for RF/FE things. 
	#IC2's transfer limit is defined by the voltage tier.
	# Default: 2048
	# Range: > 1
	transfer_rate = 2048

[big]
	#Energy storage size of the energy hatch.
	# Default: 32768
	# Range: > 1
	size = 32768
	#Defines the transfer limit for RF/FE things. 
	#IC2's transfer limit is defined by the voltage tier.
	# Default: 8192
	# Range: > 1
	transfer_rate = 8192

[huge]
	#Energy storage size of the energy hatch.
	# Default: 131072
	# Range: > 1
	size = 131072
	#Defines the transfer limit for RF/FE things. 
	#IC2's transfer limit is defined by the voltage tier.
	# Default: 32768
	# Range: > 1
	transfer_rate = 32768

[ludicrous]
	#Energy storage size of the energy hatch.
	# Default: 524288
	# Range: > 1
	size = 524288
	#Defines the transfer limit for RF/FE things. 
	#IC2's transfer limit is defined by the voltage tier.
	# Default: 131072
	# Range: > 1
	transfer_rate = 131072

[ultimate]
	#Energy storage size of the energy hatch.
	# Default: 2097152
	# Range: > 1
	size = 2097152
	#Defines the transfer limit for RF/FE things. 
	#IC2's transfer limit is defined by the voltage tier.
	# Default: 131072
	# Range: > 1
	transfer_rate = 131072

[Display]
	#Set to true, if the standard 'energy' FE (or RF) should be displayed in the tooltip of the energy hatch along with its transmission rates.
	displayFETooltip = true
	#Set to true, if IC2's energy EU should be displayed in the tooltip of the energy hatch. Will only have effect if IC2 is installed.
	displayIC2EUTooltip = true
	#Available options: 'FE', 'IC2_EU' - Default: FE - Set this to one of those 2 types to have GUI, recipe preview and energy be displayed in that type of energy in ALL ModularMachinery Reborn things.
	#Allowed Values: FE, IC2_EU
	type = "FE"
